import type { AutopilotData, AutopilotMode } from './types';

export const AUTOPILOT_MOCK_DATA: Record<AutopilotMode, AutopilotData> = {
  dynasty: {
    mode: 'dynasty',
    headline: 'Long-range roster command',
    direction: {
      label: 'Middle contender',
      confidence: 82,
      summary: 'The roster can chase wins, but the AI should protect future value and avoid buying old production unless the weekly edge is obvious.',
      strategy: 'Compete while the starting lineup is healthy. If the team slips below the top playoff tier, sell older RB production for 2026 picks or young WR value.',
      scores: [
        { label: 'Win-now push', value: 76, tone: 'good' },
        { label: 'Future value', value: 61, tone: 'warn' },
        { label: 'Trade leverage', value: 84, tone: 'info' },
      ],
      actionPlan: [
        'Hold premium young WRs unless the return includes a younger tier-up.',
        'Shop older RB production to contenders before market value softens.',
        'Use bench depth and 2nds to buy one weekly starter, not a short-window name.',
      ],
    },
    systemRead: [
      { label: 'Roster data', value: 91, tone: 'good' },
      { label: 'Market signal', value: 84, tone: 'info' },
      { label: 'History depth', value: 64, tone: 'warn' },
      { label: 'Schedule data', value: 0, tone: 'neutral' },
    ],
    lineup: [
      {
        id: 'dynasty-lineup-reed',
        type: 'Start/Sit',
        player: 'Jayden Reed',
        secondary: 'over Calvin Ridley',
        action: 'Start',
        confidence: 78,
        risk: 'Medium',
        upside: 'High',
        summary: 'Reed has the better value-growth profile and gives the lineup more weekly ceiling without sacrificing the long-term build.',
        reasons: ['Young WR profile is still gaining market trust.', 'Target growth and manufactured touches matter more than veteran floor in this build.', 'The roster can absorb some weekly variance.'],
        signals: ['Age curve', 'Dynasty value trend', 'Target opportunity', 'Roster timeline'],
        tone: 'good',
      },
      {
        id: 'dynasty-lineup-rb-insurance',
        type: 'Bench',
        player: 'Older flex RB',
        secondary: 'for high-upside WR flex',
        action: 'Bench unless role is confirmed',
        confidence: 69,
        risk: 'Medium',
        upside: 'Medium',
        summary: 'The AI would rather preserve upside in a middle-contender build than chase a low-ceiling touch projection.',
        reasons: ['Older RBs need bankable volume to justify the start.', 'The team direction does not need conservative points at every flex spot.', 'Bench choice can flip if injury news creates goal-line work.'],
        signals: ['Role certainty', 'RB shelf-life risk', 'Lineup ceiling', 'Injury news pending'],
        tone: 'info',
      },
    ],
    waivers: [
      {
        id: 'dynasty-waiver-corum',
        type: 'Waiver',
        player: 'Blake Corum',
        action: 'Pick up',
        confidence: 84,
        risk: 'Low',
        upside: 'High',
        summary: 'A young backup RB behind valuable touches is the right dynasty stash profile when the bench has disposable churn spots.',
        reasons: ['Backup RBs behind concentrated workloads can spike quickly.', 'Young profile keeps value from going to zero after one quiet week.', 'The roster has enough win-now pieces to carry one stash.'],
        signals: ['Handcuff leverage', 'Age curve', 'Market value', 'Bench churn spot'],
        tone: 'good',
      },
      {
        id: 'dynasty-waiver-te-stash',
        type: 'Waiver',
        player: 'Young TE stash',
        action: 'Add if free',
        confidence: 71,
        risk: 'Medium',
        upside: 'Medium',
        summary: 'TE breakouts are slow, but a route-growth profile is a better dynasty bench use than a low-upside veteran WR.',
        reasons: ['TE age curves reward patience.', 'Route participation matters more than one-week points.', 'Replacement-level bench WRs are easy to churn.'],
        signals: ['TE development curve', 'Route growth', 'Bench opportunity cost'],
        tone: 'info',
      },
    ],
    trades: [
      {
        id: 'dynasty-trade-henry',
        type: 'Trade',
        player: 'Derrick Henry',
        secondary: 'for young WR or 2026 pick',
        action: 'Trade away',
        confidence: 86,
        risk: 'Medium',
        upside: 'High',
        summary: 'If the roster is not clearly top tier, his name value should be converted before age and RB shelf-life risk compress the market.',
        reasons: ['Older RB value can fall fast when volume slips.', 'Contenders may still pay for current production.', 'The team direction is not pure win-now.'],
        signals: ['Age risk', 'RB shelf-life risk', 'Rebuild hedge', 'Contender demand'],
        tone: 'warn',
      },
      {
        id: 'dynasty-trade-young-wr',
        type: 'Trade',
        player: 'Rashee Rice profile',
        secondary: 'before the next value spike',
        action: 'Acquire',
        confidence: 74,
        risk: 'Medium',
        upside: 'Elite',
        summary: 'The AI likes young WRs whose value can climb from role growth rather than one unsustainable touchdown stretch.',
        reasons: ['WR value curves are more forgiving than RB curves.', 'Role growth gives both weekly and future-value upside.', 'A middle build should buy liquid assets.'],
        signals: ['Youth premium', 'Market liquidity', 'Target growth', 'Roster direction'],
        tone: 'good',
      },
    ],
    projections: [
      { player: 'Jayden Reed', position: 'WR', direction: 'Rising', currentValue: 'WR2/3 band', projectedMove: '+14%', confidence: 78, signals: ['Young WR', 'Touch growth', 'Market still catching up'] },
      { player: 'Trey McBride', position: 'TE', direction: 'Stable', currentValue: 'Elite TE', projectedMove: '+2%', confidence: 81, signals: ['Elite positional scarcity', 'Strong role', 'Already priced high'] },
      { player: 'Derrick Henry', position: 'RB', direction: 'Falling', currentValue: 'Win-now RB', projectedMove: '-18%', confidence: 86, signals: ['Age cliff', 'RB shelf life', 'Name value sell window'] },
      { player: 'Young backup RB', position: 'RB', direction: 'Rising', currentValue: 'Bench stash', projectedMove: '+22%', confidence: 67, signals: ['Injury leverage', 'Cheap acquisition', 'Role optionality'] },
    ],
    power: [
      { rank: 1, team: 'AwWQQ', direction: 'Contender', score: 92, note: 'Strong starters and clean weekly ceiling.', tone: 'good' },
      { rank: 2, team: 'PurpleHaze', direction: 'Contender', score: 84, note: 'Needs TE help but still has scoring depth.', tone: 'info' },
      { rank: 3, team: 'Skids Get Beat', direction: 'Middle contender', score: 79, note: 'Best leverage is selling excess RB value for future WR liquidity.', tone: 'warn' },
      { rank: 4, team: 'OnlyFants', direction: 'Reload', score: 72, note: 'Young core gives trade flexibility.', tone: 'info' },
    ],
    scheduleTodo: [
      'Add weekly defensive matchup scoring when the league schedule is released.',
      'Compare playoff-week opponent strength for each starter.',
      'Blend matchup difficulty into start/sit confidence without overpowering talent and role.',
    ],
  },
  redraft: {
    mode: 'redraft',
    headline: 'Current-season win maximizer',
    direction: {
      label: 'Win-now push',
      confidence: 87,
      summary: 'Future value is ignored in redraft mode. The AI should chase weekly points, role certainty, and near-term injury leverage.',
      strategy: 'Turn bench stashes into usable weekly production. Do not hold low-volume players just because they have dynasty appeal.',
      scores: [
        { label: 'Weekly ceiling', value: 83, tone: 'good' },
        { label: 'Floor safety', value: 74, tone: 'info' },
        { label: 'Bench utility', value: 58, tone: 'warn' },
      ],
      actionPlan: [
        'Prioritize players with bankable snaps, routes, carries, and red-zone usage.',
        'Cut slow-developing stashes if a player has a clearer two-week role.',
        'Trade bench value for a starter upgrade before bye weeks stack up.',
      ],
    },
    systemRead: [
      { label: 'Roster data', value: 91, tone: 'good' },
      { label: 'Season value', value: 86, tone: 'good' },
      { label: 'Usage signal', value: 72, tone: 'info' },
      { label: 'Schedule data', value: 0, tone: 'neutral' },
    ],
    lineup: [
      {
        id: 'redraft-lineup-floor',
        type: 'Start/Sit',
        player: 'High-route WR',
        secondary: 'over touchdown-only flex',
        action: 'Start',
        confidence: 81,
        risk: 'Low',
        upside: 'Medium',
        summary: 'Redraft mode favors the player with clearer weekly usage and target floor.',
        reasons: ['Routes and targets are stickier than touchdown dependency.', 'The lineup needs bankable weekly points.', 'Dynasty upside is ignored in this mode.'],
        signals: ['Route participation', 'Target share', 'Weekly floor', 'Redraft value'],
        tone: 'good',
      },
      {
        id: 'redraft-lineup-qb-rush',
        type: 'Start/Sit',
        player: 'Rushing QB',
        secondary: 'over pocket passer',
        action: 'Start',
        confidence: 76,
        risk: 'Medium',
        upside: 'High',
        summary: 'Rushing points raise the weekly ceiling and reduce dependency on passing efficiency.',
        reasons: ['Rushing QBs create points without needing perfect game script.', 'Ceiling matters when projected matchup is close.', 'Passing-only profiles need a cleaner opponent read.'],
        signals: ['Rush share', 'Weekly ceiling', 'Game script', 'Positional scarcity'],
        tone: 'info',
      },
    ],
    waivers: [
      {
        id: 'redraft-waiver-workload',
        type: 'Waiver',
        player: 'Two-week volume RB',
        action: 'Pick up',
        confidence: 85,
        risk: 'Medium',
        upside: 'High',
        summary: 'In redraft, temporary workload can matter more than long-term talent.',
        reasons: ['Near-term touches beat stash value.', 'Goal-line usage can create immediate scoring windows.', 'Bench spots should produce during bye weeks.'],
        signals: ['Snap share', 'Rush share', 'Goal-line work', 'Bye-week utility'],
        tone: 'good',
      },
      {
        id: 'redraft-waiver-wr',
        type: 'Waiver',
        player: 'Slot WR with target spike',
        action: 'Add as depth',
        confidence: 73,
        risk: 'Medium',
        upside: 'Medium',
        summary: 'The profile is useful if route growth is real, but confidence stays lower until usage repeats.',
        reasons: ['One target spike is not enough by itself.', 'Slot usage can stabilize quickly if routes stay elevated.', 'Drop candidate should be a low-snap bench stash.'],
        signals: ['Target share', 'Route trend', 'Replacement value'],
        tone: 'info',
      },
    ],
    trades: [
      {
        id: 'redraft-trade-starter',
        type: 'Trade',
        player: 'Top-18 WR starter',
        secondary: 'using two bench pieces',
        action: 'Acquire',
        confidence: 79,
        risk: 'Medium',
        upside: 'High',
        summary: 'Consolidating bench value into a weekly starter is the cleanest redraft upgrade.',
        reasons: ['Bench depth does not score unless it enters the lineup.', 'Starter upgrades compound every week.', 'Future picks and dynasty age curves do not matter here.'],
        signals: ['Starter slot value', 'Bench consolidation', 'Weekly points'],
        tone: 'good',
      },
      {
        id: 'redraft-trade-sell-name',
        type: 'Trade',
        player: 'Low-usage name value',
        secondary: 'for role certainty',
        action: 'Trade away',
        confidence: 72,
        risk: 'Medium',
        upside: 'Medium',
        summary: 'Name value should be moved if weekly usage is not matching the market price.',
        reasons: ['Redraft rewards current role, not theoretical talent.', 'Market reputation can hide declining usage.', 'A safer flex profile improves weekly decision quality.'],
        signals: ['Snap decline', 'Target decline', 'Market overvalue', 'Weekly role'],
        tone: 'warn',
      },
    ],
    projections: [
      { player: 'Volume RB fill-in', position: 'RB', direction: 'Rising', currentValue: 'Flex', projectedMove: '+19%', confidence: 80, signals: ['Immediate touches', 'Goal-line role', 'Short-term injury opening'] },
      { player: 'Low-route WR', position: 'WR', direction: 'Falling', currentValue: 'Bench name', projectedMove: '-13%', confidence: 75, signals: ['Route decline', 'Target competition', 'No long-term premium in redraft'] },
      { player: 'High-route TE', position: 'TE', direction: 'Stable', currentValue: 'Back-end TE1', projectedMove: '+4%', confidence: 69, signals: ['Route participation', 'TE scarcity', 'Touchdown variance'] },
      { player: 'Rushing QB', position: 'QB', direction: 'Rising', currentValue: 'QB1 streamer', projectedMove: '+9%', confidence: 76, signals: ['Rush floor', 'Red-zone carries', 'Weekly ceiling'] },
    ],
    power: [
      { rank: 1, team: 'AwWQQ', direction: 'Win-now', score: 91, note: 'Strongest starter projection.', tone: 'good' },
      { rank: 2, team: 'Skids Get Beat', direction: 'Playoff push', score: 84, note: 'Needs bench conversion into one weekly starter.', tone: 'info' },
      { rank: 3, team: 'PurpleHaze', direction: 'Volatile', score: 78, note: 'Ceiling is strong, but floor depends on injury news.', tone: 'warn' },
      { rank: 4, team: 'OnlyFants', direction: 'Streamer build', score: 70, note: 'Can climb with waiver aggression.', tone: 'info' },
    ],
    scheduleTodo: [
      'Add opponent defensive strength once weekly schedule data is available.',
      'Blend matchup strength into QB, streamer, and flex calls.',
      'Add playoff-week matchup planning for high-seed teams.',
    ],
  },
};
