import type {
  ManagerIntelPlayer,
  ManagerStarterPlayer,
  PlayerDetails,
  RankingPlayer,
  ReportData,
  TrendingPlayer,
  WeeklyProjectionContext,
} from "@shared/types";

export const SAMPLE_REPORT_LEAGUE_ID = "demo-sample-report";
export const SAMPLE_REPORT_LEAGUE_NAME = "Sample Dynasty League";
export const SAMPLE_REPORT_LEAGUE_FORMAT = "10-Team Dynasty SF PPR";

const GENERATED_AT = "2026-06-01T16:00:00.000Z";
const DEMO_MANAGER = "Demo Manager";
const REBUILD_MANAGER = "Rebuild Manager";
const CONTENDER_MANAGER = "Contender Manager";

type DemoPlayerId =
  | "demo-qb"
  | "demo-rb"
  | "demo-wr-alpha"
  | "demo-te"
  | "demo-te-upside"
  | "demo-wr-depth"
  | "demo-waiver-wr"
  | "demo-bench-cut"
  | "rebuild-qb"
  | "contender-rb";

function weeklyProjection(
  projectedFantasyPoints: number,
  opponent: string,
  week = 1
): WeeklyProjectionContext {
  return {
    source: "stored-weekly-projection",
    provider: "blended-weekly-context",
    season: "2026",
    week,
    scoringProfile: "ppr",
    projectedFantasyPoints,
    opponent,
    homeAway: "home",
    status: "ready",
    note: "Projection context is included for the sample report.",
  };
}

function playerDetails({
  playerId,
  fullName,
  position,
  team,
  age,
  dynastyValue,
  seasonValue,
  dynastyPositionRank,
  seasonPositionRank,
  projection,
}: {
  playerId: DemoPlayerId;
  fullName: string;
  position: string;
  team: string;
  age: number | null;
  dynastyValue: number;
  seasonValue: number;
  dynastyPositionRank: string;
  seasonPositionRank?: string;
  projection?: WeeklyProjectionContext;
}): PlayerDetails {
  return {
    playerId,
    fullName,
    position,
    team,
    age,
    weeklyProjection: projection || null,
    valueProfile: {
      dynastyValue,
      seasonValue,
      dynastyPositionRank,
      seasonPositionRank: seasonPositionRank || dynastyPositionRank,
      sources: ["Value blend"],
    },
  };
}

const playerDetailsById: Record<DemoPlayerId, PlayerDetails> = {
  "demo-qb": playerDetails({
    playerId: "demo-qb",
    fullName: "Anchor Quarterback",
    position: "QB",
    team: "BAL",
    age: 27,
    dynastyValue: 7200,
    seasonValue: 6900,
    dynastyPositionRank: "QB4",
    projection: weeklyProjection(20.8, "CIN"),
  }),
  "demo-rb": playerDetails({
    playerId: "demo-rb",
    fullName: "Fragile Runner",
    position: "RB",
    team: "GB",
    age: 25,
    dynastyValue: 5400,
    seasonValue: 5600,
    dynastyPositionRank: "RB9",
    projection: weeklyProjection(15.4, "MIN"),
  }),
  "demo-wr-alpha": playerDetails({
    playerId: "demo-wr-alpha",
    fullName: "Alpha Receiver",
    position: "WR",
    team: "DAL",
    age: 24,
    dynastyValue: 6400,
    seasonValue: 6100,
    dynastyPositionRank: "WR6",
    projection: weeklyProjection(17.2, "PHI"),
  }),
  "demo-te": playerDetails({
    playerId: "demo-te",
    fullName: "Volatile Tight End",
    position: "TE",
    team: "ATL",
    age: 25,
    dynastyValue: 4100,
    seasonValue: 3800,
    dynastyPositionRank: "TE7",
    projection: weeklyProjection(8.3, "CAR"),
  }),
  "demo-te-upside": playerDetails({
    playerId: "demo-te-upside",
    fullName: "Upside Tight End",
    position: "TE",
    team: "LAC",
    age: 24,
    dynastyValue: 4300,
    seasonValue: 5100,
    dynastyPositionRank: "TE5",
    seasonPositionRank: "TE5",
    projection: weeklyProjection(12.4, "DEN"),
  }),
  "demo-wr-depth": playerDetails({
    playerId: "demo-wr-depth",
    fullName: "Depth Receiver",
    position: "WR",
    team: "HOU",
    age: 23,
    dynastyValue: 3000,
    seasonValue: 2600,
    dynastyPositionRank: "WR34",
    seasonPositionRank: "WR41",
    projection: weeklyProjection(7.8, "IND"),
  }),
  "demo-waiver-wr": playerDetails({
    playerId: "demo-waiver-wr",
    fullName: "Breakout Waiver Receiver",
    position: "WR",
    team: "NYJ",
    age: 24,
    dynastyValue: 3600,
    seasonValue: 4300,
    dynastyPositionRank: "WR32",
    seasonPositionRank: "WR24",
    projection: weeklyProjection(13.1, "BUF"),
  }),
  "demo-bench-cut": playerDetails({
    playerId: "demo-bench-cut",
    fullName: "Last Bench Spot",
    position: "WR",
    team: "CAR",
    age: 29,
    dynastyValue: 500,
    seasonValue: 300,
    dynastyPositionRank: "WR96",
    seasonPositionRank: "WR104",
    projection: weeklyProjection(2.1, "TB"),
  }),
  "rebuild-qb": playerDetails({
    playerId: "rebuild-qb",
    fullName: "Rebuild Quarterback",
    position: "QB",
    team: "LV",
    age: 23,
    dynastyValue: 6100,
    seasonValue: 5300,
    dynastyPositionRank: "QB10",
    projection: weeklyProjection(17.5, "KC"),
  }),
  "contender-rb": playerDetails({
    playerId: "contender-rb",
    fullName: "Contender Runner",
    position: "RB",
    team: "DET",
    age: 26,
    dynastyValue: 4700,
    seasonValue: 5900,
    dynastyPositionRank: "RB16",
    seasonPositionRank: "RB8",
    projection: weeklyProjection(16.1, "CHI"),
  }),
};

function rosterPlayer(
  playerId: DemoPlayerId,
  owner = DEMO_MANAGER
): ManagerStarterPlayer & ManagerIntelPlayer {
  const details = playerDetailsById[playerId];
  const valueProfile = details.valueProfile || {};

  return {
    player_id: playerId,
    name: details.fullName || playerId,
    pos: details.position || "WR",
    owner,
    value: valueProfile.dynastyValue || 0,
    seasonValue: valueProfile.seasonValue || valueProfile.dynastyValue || 0,
    weeklyProjection: details.weeklyProjection || null,
    currentPositionRank: valueProfile.dynastyPositionRank || null,
    seasonPositionRank: valueProfile.seasonPositionRank || null,
    playerDetails: details,
  };
}

function rankingRow(
  playerId: DemoPlayerId,
  overallRank: number,
  owner: string | null = null
): RankingPlayer {
  const details = playerDetailsById[playerId];
  const valueProfile = details.valueProfile || {};

  return {
    id: playerId,
    player_id: playerId,
    name: details.fullName || playerId,
    pos: details.position || "WR",
    team: details.team || null,
    age: details.age ?? null,
    overallRank,
    positionRank: valueProfile.dynastyPositionRank || null,
    value: valueProfile.dynastyValue || 0,
    seasonValue: valueProfile.seasonValue || valueProfile.dynastyValue || 0,
    movement: 0,
    owner,
    sources: ["Value blend"],
    sourceCount: 1,
  };
}

function availableWaiverPlayer(): TrendingPlayer {
  const details = playerDetailsById["demo-waiver-wr"];

  return {
    player_id: "demo-waiver-wr",
    name: details.fullName || "Breakout Waiver Receiver",
    playerDetails: details,
    currentPositionRank: details.valueProfile?.dynastyPositionRank || "WR32",
    pos: "WR",
    team: details.team || null,
    owner: null,
    count: 940,
    ktcValue: details.valueProfile?.dynastyValue || null,
    weeklyProjection: details.weeklyProjection || null,
  };
}

const demoRoster = [
  rosterPlayer("demo-qb"),
  rosterPlayer("demo-rb"),
  rosterPlayer("demo-wr-alpha"),
  rosterPlayer("demo-te"),
  rosterPlayer("demo-te-upside"),
  rosterPlayer("demo-wr-depth"),
  rosterPlayer("demo-bench-cut"),
];
const demoStarters = [
  rosterPlayer("demo-qb"),
  rosterPlayer("demo-rb"),
  rosterPlayer("demo-wr-alpha"),
  rosterPlayer("demo-te"),
];
const demoBench = [
  rosterPlayer("demo-te-upside"),
  rosterPlayer("demo-wr-depth"),
  rosterPlayer("demo-bench-cut"),
];
const waiverTarget = availableWaiverPlayer();
const dropCandidate = rosterPlayer("demo-bench-cut");
const depthReceiver = rosterPlayer("demo-wr-depth");
const fragileRunner = rosterPlayer("demo-rb");

const demoManagerIntel: ReportData["managerRosterIntelligence"] = [
  {
    manager: DEMO_MANAGER,
    identity: "Contender with one shallow position",
    timeline: "Contender",
    summary:
      "Demo Manager has a strong quarterback and receiver core, but the roster is carrying one cuttable bench spot and thin running back depth.",
    strategySummary:
      "Turn the last bench spot into immediate waiver upside, then shop receiver depth only if it returns running back insulation.",
    starterValue: 34100,
    starterSeasonValue: 32500,
    benchValue: 9800,
    starterValuePct: 72,
    bestBenchStash: rosterPlayer("demo-te-upside"),
    weakestStarter: rosterPlayer("demo-te"),
    oldestPlayer: rosterPlayer("demo-bench-cut"),
    youngCorePlayer: rosterPlayer("demo-wr-alpha"),
    breakoutCandidate: depthReceiver,
    lastSeasonStud: rosterPlayer("demo-qb"),
    buyTarget: availableWaiverPlayer() as unknown as ManagerIntelPlayer,
    sellCandidate: fragileRunner,
    tradePlan: {
      needPosition: "RB",
      surplusPosition: "WR",
      summary:
        "Move receiver depth into a safer running back only if the return protects the weekly lineup.",
    },
    tradeBlueprints: [
      {
        label: "Depth receiver into RB insulation",
        summary:
          "Start with a receiver-depth offer to a manager with running back surplus, but do not include a core starter.",
        givePlayer: depthReceiver,
        tone: "sell",
      },
    ],
    chaosNotes: [],
    marketSignals: ["Receiver depth can be converted into running back stability."],
    pressurePoints: ["RB depth", "TE volatility", "bench churn"],
    situationSummary: {
      playerCount: demoRoster.length,
      backedCount: 2,
      strongCount: 1,
      boostCount: 1,
      riskCount: 1,
      staleCount: 0,
      sourceLimitedCount: 0,
      topBoostPlayer: "Breakout Waiver Receiver",
      topRiskPlayer: "Fragile Runner",
      note: "One available receiver clears the last bench spot while the running back room still needs protection.",
      signals: ["Available waiver upgrade", "RB depth pressure", "WR tradeable depth"],
    },
    rosterHealthScore: 82,
    positionGrades: {
      QB: { rank: 1, grade: "9", note: "Elite starter room" },
      RB: { rank: 5, grade: "5", note: "Needs one insurance piece" },
      WR: { rank: 2, grade: "8", note: "Clear surplus" },
      TE: { rank: 6, grade: "4", note: "Volatile but fixable" },
    },
    startingRosterStrength: [],
    benchBaseline: [],
    tradeableDepth: [
      {
        position: "WR",
        player: depthReceiver,
        note: "Tradeable only if the return fixes running back fragility.",
      },
    ],
    tradeChip: depthReceiver,
    injuryInsurance: null,
    rosterPlayers: demoRoster,
    benchPlayers: demoBench,
    taxiPlayers: [],
    reservePlayers: [],
    droppablePlayers: [dropCandidate],
    untouchablePlayers: [rosterPlayer("demo-qb"), rosterPlayer("demo-wr-alpha")],
    taxiTriage: {
      items: [],
      summary: "No taxi squad flags in the sample report.",
      counts: {
        "Promote Now": 0,
        "Keep Parked": 0,
        "Trade Sweetener": 0,
        Cuttable: 0,
        "Taxi Risk": 0,
      },
    },
    similarValuePlayers: {
      QB: rosterPlayer("rebuild-qb", REBUILD_MANAGER),
      RB: fragileRunner,
      WR: depthReceiver,
      TE: rosterPlayer("demo-te"),
    },
    avgAge: 25.8,
    avgAgeByPosition: { QB: 27, RB: 25, WR: 24, TE: 24.5 },
    starterAvailability: {
      avgGamesMissed: 1.2,
      riskLevel: "low",
      riskiestStarter: null,
    },
    ageFlags: [],
    holes: {
      bestQbRank: "QB4",
      rb2Rank: "RB30",
      wr3Rank: "WR34",
      te1Rank: "TE7",
      flexDepth: 4,
      summary: "Running back depth is the cleanest pressure point.",
    },
  },
  {
    manager: REBUILD_MANAGER,
    identity: "Pick-rich rebuilder",
    timeline: "Rebuild",
    summary: "Rebuild Manager has excess picks and quarterback depth, but needs starting receivers.",
    strategySummary: "Use picks and quarterback depth to acquire young receivers.",
    starterValue: 25100,
    starterSeasonValue: 23200,
    benchValue: 14200,
    starterValuePct: 58,
    bestBenchStash: rosterPlayer("rebuild-qb", REBUILD_MANAGER),
    weakestStarter: null,
    oldestPlayer: null,
    youngCorePlayer: rosterPlayer("rebuild-qb", REBUILD_MANAGER),
    breakoutCandidate: null,
    lastSeasonStud: null,
    buyTarget: depthReceiver,
    sellCandidate: rosterPlayer("rebuild-qb", REBUILD_MANAGER),
    tradePlan: {
      needPosition: "WR",
      surplusPosition: "QB",
      summary: "Use quarterback depth or picks to buy receiver stability.",
    },
    tradeBlueprints: [],
    chaosNotes: [],
    marketSignals: ["Pick surplus creates trade leverage."],
    pressurePoints: ["WR starters"],
    rosterHealthScore: 68,
    positionGrades: {
      QB: { rank: 2, grade: "8", note: "Surplus" },
      RB: { rank: 8, grade: "4", note: "Rebuild depth" },
      WR: { rank: 9, grade: "3", note: "Needs starters" },
      TE: { rank: 5, grade: "5", note: "Playable" },
    },
    startingRosterStrength: [],
    benchBaseline: [],
    tradeableDepth: [],
    tradeChip: rosterPlayer("rebuild-qb", REBUILD_MANAGER),
    injuryInsurance: null,
    rosterPlayers: [rosterPlayer("rebuild-qb", REBUILD_MANAGER)],
    benchPlayers: [],
    taxiPlayers: [],
    reservePlayers: [],
    droppablePlayers: [],
    untouchablePlayers: [rosterPlayer("rebuild-qb", REBUILD_MANAGER)],
    taxiTriage: {
      items: [],
      summary: "No taxi squad flags in the sample report.",
      counts: {
        "Promote Now": 0,
        "Keep Parked": 0,
        "Trade Sweetener": 0,
        Cuttable: 0,
        "Taxi Risk": 0,
      },
    },
    similarValuePlayers: { QB: null, RB: null, WR: null, TE: null },
    avgAge: 24.4,
    avgAgeByPosition: { QB: 23, RB: null, WR: null, TE: null },
    starterAvailability: {
      avgGamesMissed: 1.6,
      riskLevel: "medium",
      riskiestStarter: null,
    },
    ageFlags: [],
    holes: {
      bestQbRank: "QB10",
      rb2Rank: null,
      wr3Rank: null,
      te1Rank: null,
      flexDepth: 1,
      summary: "Wide receiver starters are the roster bottleneck.",
    },
  },
  {
    manager: CONTENDER_MANAGER,
    identity: "RB-heavy contender",
    timeline: "Contender",
    summary: "Contender Manager has running back depth and needs another weekly receiver.",
    starterValue: 28600,
    starterSeasonValue: 30100,
    benchValue: 7400,
    starterValuePct: 80,
    bestBenchStash: rosterPlayer("contender-rb", CONTENDER_MANAGER),
    weakestStarter: null,
    oldestPlayer: rosterPlayer("contender-rb", CONTENDER_MANAGER),
    youngCorePlayer: null,
    breakoutCandidate: null,
    lastSeasonStud: rosterPlayer("contender-rb", CONTENDER_MANAGER),
    buyTarget: depthReceiver,
    sellCandidate: rosterPlayer("contender-rb", CONTENDER_MANAGER),
    tradePlan: {
      needPosition: "WR",
      surplusPosition: "RB",
      summary: "RB depth can buy receiver points without weakening the starting lineup.",
    },
    tradeBlueprints: [],
    chaosNotes: [],
    marketSignals: ["RB depth is useful to the league market."],
    pressurePoints: ["WR depth"],
    rosterHealthScore: 74,
    positionGrades: {
      QB: { rank: 4, grade: "6", note: "Stable" },
      RB: { rank: 1, grade: "9", note: "Surplus" },
      WR: { rank: 7, grade: "4", note: "Needs help" },
      TE: { rank: 4, grade: "6", note: "Playable" },
    },
    startingRosterStrength: [],
    benchBaseline: [],
    tradeableDepth: [],
    tradeChip: rosterPlayer("contender-rb", CONTENDER_MANAGER),
    injuryInsurance: null,
    rosterPlayers: [rosterPlayer("contender-rb", CONTENDER_MANAGER)],
    benchPlayers: [rosterPlayer("contender-rb", CONTENDER_MANAGER)],
    taxiPlayers: [],
    reservePlayers: [],
    droppablePlayers: [],
    untouchablePlayers: [],
    taxiTriage: {
      items: [],
      summary: "No taxi squad flags in the sample report.",
      counts: {
        "Promote Now": 0,
        "Keep Parked": 0,
        "Trade Sweetener": 0,
        Cuttable: 0,
        "Taxi Risk": 0,
      },
    },
    similarValuePlayers: { QB: null, RB: rosterPlayer("contender-rb", CONTENDER_MANAGER), WR: null, TE: null },
    avgAge: 26.2,
    avgAgeByPosition: { QB: null, RB: 26, WR: null, TE: null },
    starterAvailability: {
      avgGamesMissed: 2.1,
      riskLevel: "medium",
      riskiestStarter: rosterPlayer("contender-rb", CONTENDER_MANAGER),
    },
    ageFlags: [],
    holes: {
      bestQbRank: null,
      rb2Rank: "RB8",
      wr3Rank: null,
      te1Rank: null,
      flexDepth: 2,
      summary: "Wide receiver depth is the place to attack.",
    },
  },
];

const rankingRows = [
  rankingRow("demo-qb", 18, DEMO_MANAGER),
  rankingRow("demo-wr-alpha", 27, DEMO_MANAGER),
  rankingRow("rebuild-qb", 32, REBUILD_MANAGER),
  rankingRow("demo-rb", 44, DEMO_MANAGER),
  rankingRow("contender-rb", 59, CONTENDER_MANAGER),
  rankingRow("demo-te-upside", 84, DEMO_MANAGER),
  rankingRow("demo-te", 91, DEMO_MANAGER),
  rankingRow("demo-wr-depth", 126, DEMO_MANAGER),
  rankingRow("demo-waiver-wr", 112, null),
  rankingRow("demo-bench-cut", 310, DEMO_MANAGER),
];

export function createSampleReportData(): ReportData {
  return {
    leagueId: SAMPLE_REPORT_LEAGUE_ID,
    leagueValueMode: "dynasty",
    viewerManager: DEMO_MANAGER,
    leagueDiagnostics: {
      teamCount: 10,
      valueMode: "dynasty",
      qbFormat: "superflex",
      currentSeason: "2026",
      currentWeek: 1,
      draftStatus: "complete",
      rosterSlots: ["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "SUPER_FLEX", "BN"],
      starterSlots: ["QB", "RB", "RB", "WR", "WR", "TE", "FLEX", "SUPER_FLEX"],
      totalRosterSlots: 16,
      lineupSlotSummary: "1 QB, 2 RB, 2 WR, 1 TE, Flex, Superflex",
      starterCountSummary: "8 starters",
      starterCalculation: "League starter slots",
      benchCalculation: "Bench value",
      tradeableDepthCalculation: "Tradeable depth",
      scoringSummary: "PPR",
      receptionScoring: 1,
      tightEndPremium: 0,
      ktcProfileLabel: "Dynasty SF PPR",
      valueSnapshotProfileCount: 1,
      valueSnapshotProfiles: ["Dynasty SF PPR"],
      valueLimitations: [],
      aiConfidence: {
        score: 68,
        previousScore: 61,
        scoreDelta: 7,
        label: "Building confidence",
        note: "Confidence rises as league history, manager behavior, source trust, and snapshot memory accumulate.",
        signals: [
          {
            key: "leagueHistory",
            label: "League history",
            score: 56,
            previousScore: 44,
            scoreDelta: 12,
            weight: 0.24,
            status: "building",
            note: "The sample has trade, waiver, and roster-context history.",
          },
          {
            key: "managerActivity",
            label: "Manager activity",
            score: 72,
            previousScore: 66,
            scoreDelta: 6,
            weight: 0.12,
            status: "building",
            note: "Recent waiver and trade signals are available.",
          },
        ],
      },
    },
    transactionBackfillDiagnostics: {
      checkedLeagueCount: 2,
      seasonCount: 2,
      transactionCount: 14,
      waiverOrFreeAgentCount: 5,
      tradeProposalCount: 2,
      completedTradeCount: 1,
      leagues: [
        {
          leagueId: "demo-history-2025",
          season: "2025",
          transactionCount: 8,
          status: "loaded",
        },
        {
          leagueId: "demo-history-2024",
          season: "2024",
          transactionCount: 6,
          status: "loaded",
        },
      ],
      generatedAt: GENERATED_AT,
    },
    currentStandings: [
      { rosterId: 1, manager: DEMO_MANAGER, rank: 2, wins: 8, losses: 5, ties: 0, pointsFor: 1742 },
      { rosterId: 2, manager: REBUILD_MANAGER, rank: 9, wins: 4, losses: 9, ties: 0, pointsFor: 1388 },
      { rosterId: 3, manager: CONTENDER_MANAGER, rank: 4, wins: 7, losses: 6, ties: 0, pointsFor: 1685 },
    ],
    standingsHistory: [],
    managerAvatars: {},
    managerChampionships: {},
    playerDetailsById,
    currentPositionRankById: {
      "demo-qb": "QB4",
      "demo-rb": "RB9",
      "demo-wr-alpha": "WR6",
      "demo-te": "TE7",
      "demo-te-upside": "TE5",
      "demo-wr-depth": "WR34",
      "demo-waiver-wr": "WR32",
      "demo-bench-cut": "WR96",
      "rebuild-qb": "QB10",
      "contender-rb": "RB16",
    },
    managerRosterValueGrowth: [
      { manager: DEMO_MANAGER, past_val: 42100, total_val: 43900, growth: 1800, rank: 1 },
      { manager: CONTENDER_MANAGER, past_val: 36300, total_val: 37400, growth: 1100, rank: 2 },
      { manager: REBUILD_MANAGER, past_val: 38500, total_val: 39300, growth: 800, rank: 3 },
    ],
    weeklyRisers: [
      {
        name: "Depth Receiver",
        player_id: "demo-wr-depth",
        playerDetails: playerDetailsById["demo-wr-depth"],
        owner: DEMO_MANAGER,
        pos: "WR",
        val_last: 2600,
        val_now: 3000,
        diff: 400,
        pct_change: 15.4,
      },
      {
        name: "Breakout Waiver Receiver",
        player_id: "demo-waiver-wr",
        playerDetails: playerDetailsById["demo-waiver-wr"],
        owner: "Available",
        pos: "WR",
        val_last: 2600,
        val_now: 3600,
        diff: 1000,
        pct_change: 38.5,
      },
    ],
    weeklyFallers: [
      {
        name: "Fragile Runner",
        player_id: "demo-rb",
        playerDetails: playerDetailsById["demo-rb"],
        owner: DEMO_MANAGER,
        pos: "RB",
        val_last: 5900,
        val_now: 5400,
        diff: -500,
        pct_change: -8.5,
      },
    ],
    depthChartMovers: {
      windowDays: 7,
      currentSnapshotKey: "2026-06-01",
      baselineSnapshotKey: "2026-05-25",
      generatedAt: GENERATED_AT,
      up: [
        {
          playerId: "demo-wr-depth",
          playerName: "Depth Receiver",
          owner: DEMO_MANAGER,
          team: "HOU",
          position: "WR",
          kind: "promoted-to-starter",
          direction: "up",
          previousRank: 3,
          currentRank: 1,
          previousSlot: "WR3",
          currentSlot: "WR1",
          confidence: 82,
          note: "Depth Receiver moved from WR3 to WR1.",
          source: "espn-depth-charts-v1",
          currentSnapshotKey: "2026-06-01",
          baselineSnapshotKey: "2026-05-25",
          currentPositionRank: "WR34",
        },
        {
          playerId: "demo-waiver-wr",
          playerName: "Breakout Waiver Receiver",
          owner: null,
          team: "NYJ",
          position: "WR",
          kind: "rank-improved",
          direction: "up",
          previousRank: 4,
          currentRank: 2,
          previousSlot: "WR4",
          currentSlot: "WR2",
          confidence: 74,
          note: "Breakout Waiver Receiver moved from WR4 to WR2.",
          source: "espn-depth-charts-v1",
          currentSnapshotKey: "2026-06-01",
          baselineSnapshotKey: "2026-05-25",
          currentPositionRank: "WR32",
        },
      ],
      down: [
        {
          playerId: "demo-rb",
          playerName: "Fragile Runner",
          owner: DEMO_MANAGER,
          team: "GB",
          position: "RB",
          kind: "demoted-from-starter",
          direction: "down",
          previousRank: 1,
          currentRank: 3,
          previousSlot: "RB1",
          currentSlot: "RB3",
          confidence: 82,
          note: "Fragile Runner moved from RB1 to RB3.",
          source: "espn-depth-charts-v1",
          currentSnapshotKey: "2026-06-01",
          baselineSnapshotKey: "2026-05-25",
          currentPositionRank: "RB9",
        },
      ],
    },
    rankings: {
      generatedAt: GENERATED_AT,
      defaultProfileKey: "demo-dynasty-sf",
      selectedProfileKey: "demo-dynasty-sf",
      selectedProfileLabel: "Dynasty SF",
      profileOptions: [
        { key: "demo-dynasty-sf", label: "Dynasty SF", board: "dynasty", qbFormat: "sf", tep: 0 },
      ],
      sourceWeightProfiles: {
        "demo-dynasty-sf": {
          label: "Value blend",
          sources: [
            {
              key: "value-blend",
              source: "Value blend",
              weight: 1,
              percent: 100,
              note: "Demo ranking weight.",
            },
          ],
        },
      },
      profiles: { "demo-dynasty-sf": rankingRows },
      profileRowCounts: { "demo-dynasty-sf": rankingRows.length },
      identityDiagnostics: [],
      dynastySf: rankingRows,
      dynastyOneQb: rankingRows,
      devySf: [],
      devyOneQb: [],
    },
    trendingAdds: [waiverTarget],
    trendingDrops: [],
    leagueOverview: [
      { manager: DEMO_MANAGER, total_val: 43900, rank_qb: 1, rank_rb: 5, rank_wr: 2, rank_te: 6, rank_value: 1, rank_2027: 5 },
      { manager: CONTENDER_MANAGER, total_val: 37400, rank_qb: 4, rank_rb: 1, rank_wr: 7, rank_te: 4, rank_value: 2, rank_2027: 6 },
      { manager: REBUILD_MANAGER, total_val: 39300, rank_qb: 2, rank_rb: 8, rank_wr: 9, rank_te: 5, rank_value: 3, rank_2027: 1 },
    ],
    projectedRisers: [],
    projectedFallers: [],
    tradeProfitLeaderboard: [
      { rank: 1, manager: CONTENDER_MANAGER, profit: 800, wins: 1, trade_count: 1 },
      { rank: 2, manager: DEMO_MANAGER, profit: -800, wins: 0, trade_count: 1 },
    ],
    tradeHistory: [
      {
        date: "2026-05-21",
        season: "2026",
        team_a: DEMO_MANAGER,
        team_b: CONTENDER_MANAGER,
        team_a_items: "2026 2nd",
        team_b_items: "PLAYER:demo-wr-depth|Depth Receiver|3000",
        team_a_total: 2200,
        team_b_total: 3000,
        point_gap: 800,
        winner: CONTENDER_MANAGER,
        winners: [CONTENDER_MANAGER],
      },
    ],
    positionDepth: [
      { manager: DEMO_MANAGER, position: "WR", count: 8, status: "excess" },
      { manager: DEMO_MANAGER, position: "RB", count: 4, status: "shortage" },
      { manager: CONTENDER_MANAGER, position: "RB", count: 7, status: "excess" },
      { manager: REBUILD_MANAGER, position: "WR", count: 4, status: "shortage" },
    ],
    managerPositionCounts: [
      {
        manager: DEMO_MANAGER,
        activePlayerCount: 15,
        reservePlayerCount: 0,
        taxiPlayerCount: 0,
        totalRosterPlayerCount: 15,
        QB: 3,
        QB_starters: 2,
        RB: 4,
        RB_starters: 2,
        WR: 8,
        WR_starters: 3,
        TE: 3,
        TE_starters: 1,
        starterPlayers: demoStarters,
        lineupPlayers: demoRoster,
        rosterPlayers: demoRoster,
        starterGroups: [
          { key: "QB", label: "QB", count: 1, players: [rosterPlayer("demo-qb")] },
          { key: "RB", label: "RB", count: 1, players: [rosterPlayer("demo-rb")] },
          { key: "WR", label: "WR", count: 1, players: [rosterPlayer("demo-wr-alpha")] },
          { key: "TE", label: "TE", count: 1, players: [rosterPlayer("demo-te")] },
        ],
      },
      {
        manager: REBUILD_MANAGER,
        activePlayerCount: 15,
        reservePlayerCount: 0,
        taxiPlayerCount: 0,
        totalRosterPlayerCount: 15,
        QB: 4,
        QB_starters: 2,
        RB: 5,
        RB_starters: 2,
        WR: 4,
        WR_starters: 2,
        TE: 2,
        TE_starters: 1,
        starterPlayers: [rosterPlayer("rebuild-qb", REBUILD_MANAGER)],
        lineupPlayers: [rosterPlayer("rebuild-qb", REBUILD_MANAGER)],
        rosterPlayers: [rosterPlayer("rebuild-qb", REBUILD_MANAGER)],
      },
      {
        manager: CONTENDER_MANAGER,
        activePlayerCount: 15,
        reservePlayerCount: 0,
        taxiPlayerCount: 0,
        totalRosterPlayerCount: 15,
        QB: 3,
        QB_starters: 2,
        RB: 7,
        RB_starters: 3,
        WR: 4,
        WR_starters: 2,
        TE: 2,
        TE_starters: 1,
        starterPlayers: [rosterPlayer("contender-rb", CONTENDER_MANAGER)],
        lineupPlayers: [rosterPlayer("contender-rb", CONTENDER_MANAGER)],
        rosterPlayers: [rosterPlayer("contender-rb", CONTENDER_MANAGER)],
      },
    ],
    managerRosterIntelligence: demoManagerIntel,
    tradeTendencies: [
      {
        manager: DEMO_MANAGER,
        tradeCount: 1,
        wins: 0,
        winPct: 0,
        profit: -800,
        avgGap: 800,
        favoritePartner: CONTENDER_MANAGER,
        overpaysForPicks: false,
        overpaysForVeterans: false,
      },
      {
        manager: CONTENDER_MANAGER,
        tradeCount: 1,
        wins: 1,
        winPct: 100,
        profit: 800,
        avgGap: 800,
        favoritePartner: DEMO_MANAGER,
        overpaysForPicks: false,
        overpaysForVeterans: false,
      },
    ],
    powerRankings: [
      { rank: 1, manager: DEMO_MANAGER, score: 84, tier: "Heavyweight", starterStrength: 88, rosterValue: 91, positionalBalance: 74, draftCapital: 58, youthScore: 72, tradeEfficiency: 80 },
      { rank: 2, manager: CONTENDER_MANAGER, score: 76, tier: "Contender", starterStrength: 82, rosterValue: 79, positionalBalance: 68, draftCapital: 54, youthScore: 63, tradeEfficiency: 74 },
      { rank: 3, manager: REBUILD_MANAGER, score: 70, tier: "Rebuilder", starterStrength: 68, rosterValue: 82, positionalBalance: 56, draftCapital: 92, youthScore: 84, tradeEfficiency: 60 },
    ],
    dynastyTimelines: [
      { manager: DEMO_MANAGER, contenderScore: 88, outlook2027: 78, agingRisk: 28, rebuildScore: 20, label: "Contend" },
      { manager: CONTENDER_MANAGER, contenderScore: 82, outlook2027: 66, agingRisk: 38, rebuildScore: 26, label: "Contend" },
      { manager: REBUILD_MANAGER, contenderScore: 42, outlook2027: 85, agingRisk: 18, rebuildScore: 88, label: "Rebuild" },
    ],
    pickPortfolios: [
      {
        manager: DEMO_MANAGER,
        value2026: 1700,
        value2027: 2500,
        count2025: 0,
        count2026: 2,
        count2027: 3,
        value2025: 0,
        totalValue: 4200,
        ownPicks: 3,
        acquiredPicks: 2,
        projectedSlots: ["mid 1st"],
        futurePicks: [
          { id: "demo-2026-2", label: "2026 2nd", manager: DEMO_MANAGER, originalOwner: DEMO_MANAGER, season: "2026", round: 2, value: 900 },
          { id: "demo-2027-1", label: "2027 1st", manager: DEMO_MANAGER, originalOwner: DEMO_MANAGER, season: "2027", round: 1, value: 2100 },
        ],
      },
      {
        manager: REBUILD_MANAGER,
        value2026: 5200,
        value2027: 4900,
        count2025: 0,
        count2026: 5,
        count2027: 5,
        value2025: 0,
        totalValue: 10100,
        ownPicks: 5,
        acquiredPicks: 5,
        projectedSlots: ["early 1st"],
        futurePicks: [
          { id: "rebuild-2026-1", label: "2026 1st", manager: REBUILD_MANAGER, originalOwner: REBUILD_MANAGER, season: "2026", round: 1, value: 3000 },
          { id: "rebuild-2027-1", label: "2027 1st", manager: REBUILD_MANAGER, originalOwner: DEMO_MANAGER, season: "2027", round: 1, value: 2400 },
        ],
      },
    ],
    waiverIntelligence: {
      rosteredTrendingAdds: [],
      availableTrendingAdds: [waiverTarget],
      highestKtcAvailable: waiverTarget,
      bestAvailableByPosition: {
        QB: null,
        RB: null,
        WR: waiverTarget,
        TE: null,
        K: null,
        DEF: null,
      },
      bestTaxiStashes: [],
      recentlyDroppedValuable: [],
      omittedCandidates: [],
    },
    recentTransactions: [
      {
        id: "demo-waiver-1",
        date: "2026-05-30T00:00:00.000Z",
        manager: REBUILD_MANAGER,
        type: "Waiver",
        bidAmount: 7,
        addedPlayer: {
          player_id: "demo-wr-depth",
          name: "Depth Receiver",
          playerDetails: playerDetailsById["demo-wr-depth"],
          currentPositionRank: "WR34",
          pos: "WR",
          team: "HOU",
          ktcValue: 3000,
        },
        droppedPlayer: null,
        alternativeDrop: null,
        note: "Winning claim logged.",
        losingBidsAvailable: false,
      },
      {
        id: "demo-waiver-2",
        date: "2026-05-29T00:00:00.000Z",
        manager: DEMO_MANAGER,
        type: "Waiver",
        bidAmount: 4,
        addedPlayer: {
          player_id: "demo-te-upside",
          name: "Upside Tight End",
          playerDetails: playerDetailsById["demo-te-upside"],
          currentPositionRank: "TE5",
          pos: "TE",
          team: "LAC",
          ktcValue: 4300,
        },
        droppedPlayer: {
          player_id: "demo-bench-cut",
          name: "Last Bench Spot",
          playerDetails: playerDetailsById["demo-bench-cut"],
          currentPositionRank: "WR96",
          pos: "WR",
          team: "CAR",
          ktcValue: 500,
        },
        alternativeDrop: null,
        note: "Winning claim logged.",
        losingBidsAvailable: false,
      },
    ],
    draftPicks: [],
    draftStats: [],
  };
}
